[package]
name = "citrea-stf"
version = { workspace = true }
edition = { workspace = true }
resolver = "2"
authors = { workspace = true }
license = { workspace = true }
homepage = "sovereign.xyz"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
clap = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
jsonrpsee = { workspace = true, features = [
    "server",
    "http-client",
], optional = true }
# tracing = { workspace = true }

sov-stf-runner = { path = "../../../full-node/sov-stf-runner", optional = true }
sov-rollup-interface = { path = "../../../rollup-interface" }
sov-cli = { path = "../../../module-system/sov-cli", optional = true }

sov-modules-stf-blueprint = { path = "../../../module-system/sov-modules-stf-blueprint" }
sov-accounts = { path = "../../../module-system/module-implementations/sov-accounts" }
sov-state = { path = "../../../module-system/sov-state" }
sov-modules-api = { path = "../../../module-system/sov-modules-api" }
sov-evm = { path = "../../../module-system/module-implementations/sov-evm" }
soft-confirmation-rule-enforcer = { path = "../../../module-system/module-implementations/soft-confirmation-rule-enforcer" }


[dev-dependencies]
citrea-stf = { path = ".", features = ["native"] }
tempfile = { workspace = true }
rand = { workspace = true }
sov-data-generators = { path = "../../../module-system/utils/sov-data-generators" }
sov-mock-zkvm = { path = "../../../adapters/mock-zkvm" }
sov-prover-storage-manager = { path = "../../../full-node/sov-prover-storage-manager", features = [
    "test-utils",
] }


[features]
default = []
native = [
    "clap",
    "sov-stf-runner/native",
    "dep:sov-cli",
    "sov-accounts/native",
    "sov-evm/native",
    "sov-modules-api/native",
    "sov-rollup-interface/native",
    "sov-modules-stf-blueprint/native",
    "serde",
    "serde_json",
    "jsonrpsee",
    "toml",
]
serde = [
    "sov-accounts/serde",
    "sov-evm/serde",
    "soft-confirmation-rule-enforcer/serde",
    "dep:serde",
]
