tracing_debug="$TRACING_DEBUG"
host="$HOST"
port=$PORT
network="$NETWORK"
secret_key="$SECRET_KEY"
num_verifiers=$NUM_VERIFIERS
user_takes_after=$USER_TAKES_AFTER
confirmation_threshold=$CONFIRMATION_THRESHOLD
bitcoin_rpc_url="$BITCOIN_RPC_URL"
bitcoin_rpc_user="$BITCOIN_RPC_USER"
bitcoin_rpc_password="$BITCOIN_RPC_PASSWORD"
db_host="$DB_HOST"
db_port=$DB_PORT
db_user="$DB_USER"
db_password="$DB_PASSWORD"
db_name="$DB_NAME"
verifiers_public_keys=[
"$VERIFIER_1_PUBLIC_KEY",
"$VERIFIER_2_PUBLIC_KEY",
"$VERIFIER_3_PUBLIC_KEY",
"$VERIFIER_4_PUBLIC_KEY",
"$VERIFIER_5_PUBLIC_KEY",
"$VERIFIER_6_PUBLIC_KEY",
"$VERIFIER_7_PUBLIC_KEY",
]
num_operators=$NUM_OPERATORS
operators_xonly_pks =[
"$OPERATOR_1_XONLY_PKS",
"$OPERATOR_2_XONLY_PKS",
"$OPERATOR_3_XONLY_PKS",
]
operator_wallet_addresses=[
"$OPERATOR_1_WALLET_ADDR",
"$OPERATOR_2_WALLET_ADDR",
"$OPERATOR_3_WALLET_ADDR",
]
operator_withdrawal_fee_sats=$OPERATOR_WITHDRAWAL_FEE_SATS
bridge_amount_sats=$BRIDGE_AMOUNT_SATS
operator_takes_after=$OPERATOR_TAKES_AFTER
operator_num_kickoff_utxos_per_tx=$OPERATOR_NUM_KICKOFF_UTXOS_PER_TX
citrea_rpc_url="$CITREA_RPC_URL"
bridge_contract_address="$BRIDGE_CONTRACT_ADDRESS"
