[public_keys]
sequencer_public_key = "4682a70af1d3fae53a5a26b682e2e75f7a1de21ad5fc8d61794ca889880d39d1"
sequencer_da_pub_key = "03015a7c4d2cc1c771198686e2ebef6fe7004f4136d61f6225b061d1bb9b821b9b"
prover_da_pub_key = "0357d255ab93638a2d880787ebaadfefdfc9bb51a26b4a37e5d588e04e54c60a42"

[da]
# put in the url of your Bitcoin node
node_url = "http://127.0.0.1:18443"

#  put in the username and password of your Bitcoin node
node_username = "chainway"
node_password = "topsecret"

# leave this as is
network = "testnet"
tx_backup_dir = "resources/bitcoin/inscription_txs"

[storage]
path = "resources/dbs/prover-db"
db_max_open_files = 5000

[rpc]
bind_host = "0.0.0.0"
bind_port = 8080
enable_subscriptions = false
# for below if you don't want to use default values
# comment out and set to desired value

# max connections are deafult to 100
# max_connections = 100

# max request body size is default to 10MB
# max_request_body_size = 1048576

# max response body size is default to 10MB
max_response_body_size = 1048576000

# max batch rpc requests count it default to 50
# batch_requests_limit = 50

#  subscriptions are enabled by default
# enable_subscriptions = true

# max subscriptions per connection is default to 100
# max_subscriptions_per_connection = 100

[runner]
sequencer_client_url = "https://rpc.testnet.citrea.xyz"

# if you want to store full soft confirmations in your node
# set this to true
include_tx_body = false
# --da-layer bitcoin --genesis-paths ./resources/genesis/testnet --rollup-config-path ./resources/configs/testnet/prover_rollup_config.toml --prover-config-path ./resources/configs/testnet/prover_config.toml
sync_blocks_count = 20
