[public_keys]
sequencer_public_key="$ROLLUP__PUBLIC_KEYS__SEQUENCER_PUBLIC_KEY"
sequencer_da_pub_key="$ROLLUP__PUBLIC_KEYS__SEQUENCER_DA_PUB_KEY"
prover_da_pub_key="$ROLLUP__PUBLIC_KEYS__PROVER_DA_PUB_KEY"

[da]
node_url="$ROLLUP__DA__NODE_URL"
node_username="$ROLLUP__DA__NODE_USERNAME"
node_password="$ROLLUP__DA__NODE_PASSWORD"
network="$ROLLUP__DA__NETWORK"
tx_backup_dir="$ROLLUP__DA__TX_BACKUP_DIR"
da_private_key="$ROLLUP__DA__DA_PRIVATE_KEY"

[storage]
path="$ROLLUP__STORAGE__PATH"
db_max_open_files=$ROLLUP__STORAGE__DB_MAX_OPEN_FILES

[rpc]
bind_host="$ROLLUP__RPC__BIND_HOST"
bind_port=$ROLLUP__RPC__BIND_PORT
max_connections=$ROLLUP__RPC__MAX_CONNECTIONS
max_request_body_size=$ROLLUP__RPC__MAX_REQUEST_BODY_SIZE
max_response_body_size=$ROLLUP__RPC__MAX_RESPONSE_BODY_SIZE
batch_requests_limit=$ROLLUP__RPC__BATCH_REQUESTS_LIMIT
enable_subscriptions=$ROLLUP__RPC__ENABLE_SUBSCRIPTIONS
max_subscriptions_per_connection=$ROLLUP__RPC__MAX_SUBSCRIPTIONS_PER_CONNECTION
