private_key="$SEQUENCER__PRIVATE_KEY"
min_soft_confirmations_per_commitment=$SEQUENCER__MIN_SOFT_CONFIRMATIONS_PER_COMMITMENT
test_mode=$SEQUENCER__TEST_MODE
deposit_mempool_fetch_limit=$SEQUENCER__DEPOSIT_MEMPOOL_FETCH_LIMIT
block_production_interval_ms=$SEQUENCER__BLOCK_PRODUCTION_INTERVAL_MS
da_update_interval_ms=$SEQUENCER__DA_UPDATE_INTERVAL_MS

[mempool_conf]
pending_tx_limit=$SEQUENCER__MEMPOOL_CONF__PENDING_TX_LIMIT
pending_tx_size=$SEQUENCER__MEMPOOL_CONF__PENDING_TX_SIZE
queue_tx_limit=$SEQUENCER__MEMPOOL_CONF__QUEUE_TX_LIMIT
queue_tx_size=$SEQUENCER__MEMPOOL_CONF__QUEUE_TX_SIZE
base_fee_tx_limit=$SEQUENCER__MEMPOOL_CONF__BASE_FEE_TX_LIMIT
base_fee_tx_size=$SEQUENCER__MEMPOOL_CONF__BASE_FEE_TX_SIZE
max_account_slots=$SEQUENCER__MEMPOOL_CONF__MAX_ACCOUNT_SLOTS
